---

  - name: install the latest version of yum packages {{ ansible_pkg_mgr}}
    become: yes
    yum:
      name: "{{ item }}"      
      state: latest
      lock_timeout: 180
    loop: "{{ yumPackages }}"  



